### ISSUE TITLE
Add Integration Events to Whitelist

### ISSUE THREAD

**Issue by flynfish** [ssaunier/github_webhook#11]
It's not currently listed [here](https://developer.github.com/v3/activity/events/types/) because it is in early access. Could you add it to whitelist or perhaps there should be an early access whitelist and flag to enable it?

https://developer.github.com/early-access/integrations/webhooks/

`integration_installation`
`integration_installation_repositories`

**Comment by ssaunier** [comment]
Sure! I added it to the whitelist and released [1.0.3](https://rubygems.org/gems/github_webhook/versions/1.0.4). Cheers!

**Comment by flynfish** [comment]
Awesome thanks!
