### ISSUE TITLE
Could this gem be rails independent? 

### ISSUE THREAD

**Issue by oliverswitzer** [ssaunier/github_webhook#19]
Was hoping to make use of this really useful gem for my simple sinatra app but unfortunately it looks like it depends on Rails concerns and active support. 

This doesn't seem super necessary, however, and was wondering about the possibility of making this gem capable of working without being used in a rails context?

**Comment by ssaunier** [comment]
You're right I could have avoided it, the implementation I chose was to be plug & play in a Rails controller. It uses 2 features of ActiveSupport:

- Concerns
- HashWithIndifferentAccess

All the logic is in this file: https://github.com/ssaunier/github_webhook/blob/master/lib/github_webhook/processor.rb

**Comment by nickhammond** [comment]
@chrismytton built something similar for Sinatra https://github.com/chrismytton/sinatra-github_webhooks.

**Comment by chrismytton** [comment]
Thanks for the plug, @nickhammond 🙂 

I also made a pure Rack solution [rack-github_webhooks](https://github.com/chrismytton/rack-github_webhooks), which works without Sinatra or Rails.

**Comment by ssaunier** [comment]
Thank you @nickhammond & @chrismytton!

Closing this issue as there are alternative gems now 🍾

**Comment by ssaunier** [comment]
FYI I added those two alternatives to the [`README`](https://github.com/ssaunier/github_webhook#alternatives)
