### ISSUE TITLE
Use of "send" allows remote execution of any method on controllers that include GithubWebhook::Processor

### ISSUE THREAD

**Issue by synthead** [ssaunier/github_webhook#2]
In the `create` method, [`send` is executed](https://github.com/ssaunier/github_webhook/blob/34db8301ada23ebb2c8e70bcabae9866a78f2939/lib/github_webhook/processor.rb#L13)...

```ruby
  def create
    if self.respond_to? event
      self.send event, json_body
      head(:ok)
    else
      raise NoMethodError.new("GithubWebhooksController##{event} not implemented")
    end
  end
```

...against [user input via the X-GitHub-Event value from the HTTP headers](https://github.com/ssaunier/github_webhook/blob/34db8301ada23ebb2c8e70bcabae9866a78f2939/lib/github_webhook/processor.rb#L54):

```ruby
  def event
    @event ||= request.headers['X-GitHub-Event'].to_sym
  end
```

Therefore, by creating a request with an arbitrary value for X-GitHub-Event, it is possible to execute any method available on the controller handling these requests.  As an example, in your [README.md](https://github.com/ssaunier/github_webhook/tree/b894b2046a4946ee005c2807d696dc1cb5ccd9c5#configuration), the `GithubWebhooksController` is afffected:

```ruby
# app/controllers/github_webhooks_controller.rb
class GithubWebhooksController < ActionController::Base
  include GithubWebhook::Processor

  def push(payload)
    # TODO: handle push webhook
  end

  def webhook_secret(payload)
    ENV['GITHUB_WEBHOOK_SECRET']
  end
end
```

A couple ideas come to mind to fix this:
* Use a case statement on the X-GitHub-Event value and call the appropriate method.
* Create a whitelist of allowed methods that can be issued to `send`.

**Comment by synthead** [comment]
Wow, thanks for the quick fix! Any chance you could tag a minor release for this so we can have an updated gem on rubygems.org?

**Comment by ssaunier** [comment]
Yes, `0.3.0` is out :)

**Comment by ssaunier** [comment]
When upgrading, make sure to prefix your event handlers with `github_`, see [the updated README](https://github.com/ssaunier/github_webhook#configuration)
