### ISSUE TITLE
Please add pull_request_review to GITHUB_EVENTS_WHITELIST

### ISSUE THREAD

**Issue by monfresh** [ssaunier/github_webhook#9]
GitHub added some new webhook events recently, such as `pull_request_review`. Could you please add them to the whitelisted array? Thanks! Great gem by the way.

https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent

**Comment by ssaunier** [comment]
Sure! [1.0.2](https://rubygems.org/gems/github_webhook) has now been released.

**Comment by monfresh** [comment]
Wow, that was fast! Thanks!
